name: PDALab3VisualizationTest
channels:
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=7.0.1
  - pip=24.2
  - python=3.10.15
  - setuptools=75.1.0
  - pip:
      - ffmpeg-python==0.2.0
      - future==1.0.0
      - glfw==2.7.0
      - numpy==2.1.3
      - pyopengl==3.1.7
      - sortedcontainers==2.4.0